<?php

/**
 * LLMesh Demo 02: Streaming Text Generation (OpenAI)
 *
 * This script demonstrates how to stream text generated by OpenAI GPT-4o in real-time,
 * printing each chunk immediately as it arrives instead of waiting for the full response.
 */

// Load the bootstrap file to handle autoloading and API key setup.
$apiKey = require __DIR__ . '/bootstrap.php';

use LLMesh\Core\LLMesh;
use LLMesh\Core\Generators\GenerateTextOptions;
use LLMesh\OpenAI\OpenAIProvider;

echo "=== LLMesh OpenAI Streaming Text Demo ===\n\n";

try {
    $provider = new OpenAIProvider($apiKey);

    $prompt = 'Write a short, engaging 2-paragraph story about a programmer discovering space travel.';
    echo "Prompt: \"{$prompt}\"\n\n";

    $options = GenerateTextOptions::make()->withPrompt($prompt);

    echo "Streaming Response from OpenAI:\n";
    echo "------------------------------------------------\n";

    // 1. Initiate Streaming
    // streamText returns a StreamResponse, which is lazy.
    // It will only execute the network call when we start iterating.
    $stream = LLMesh::streamText($provider, $options);

    // 2. Iterate Over the Stream
    // We loop through the stream object directly using a foreach loop.
    // Each item yielded is a ChunkDelta object containing a 'text' property.
    foreach ($stream as $chunk) {
        echo $chunk->text;
        
        // flush() forces PHP to output the text immediately
        flush();
    }
    echo "\n------------------------------------------------\n\n";

    echo "Stream completed successfully!\n";

} catch (\Throwable $e) {
    echo "\n❌ Error occurred during streaming: " . $e->getMessage() . "\n";
}
